### PR TITLE
Make cache not reuse results from different instances of same type

### LINKED ISSUE #6: Same method, different instance, same results
I have this test to illustrate the problem. I assumed calling the same method on a different class would give different results.

While this can be interesting in some scenarios, I consider that caching scope feel more natural in a per-class fashion.

```
public class MemoizerTests
{
    [Fact]
    public void Cached_method_in_different_instances_should_return_different_results()
    {
        var i1 = new MyClass("hello");
        var i2 = new MyClass("how are you?");

        var one = i1.Get();
        var two = i2.Get();
        Assert.NotEqual(one, two);
    }

    class MyClass
    {
        private string payload;

        public MyClass(string payload)
        {
            this.payload = payload;
        }

        [Cache]
        public string Get() => payload;
    }
}
```

Does it make sense to create an option in the `CacheAttribute` to choose the scope level? 
- per-type
- per-instance

### PR DESCRIPTION
**Pull request by SuperJMN**
Fixes https://github.com/Gaweph/Memoizer/issues/6

### CODE REVIEW

**Comment by Gaweph** [comment]
Brilliant,  Thanks José,

Do you think it might be safer to use `ObjectIDGenerator` instead of  `target.GetHashCode()` perhaps?  As we can't guarantee that the `GetHashCode` is telling us it's the same object reference.  And we can't be sure what the `GetHashCode` is doing as it can be overwritten (it could be changing because of some internal state for example).

Info here:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.objectidgenerator?view=netstandard-2.0

What are your thoughts?

**Comment by SuperJMN** [comment]
> Brilliant, Thanks José,
> 
> Do you think it might be safer to use `ObjectIDGenerator` instead of `target.GetHashCode()` perhaps? As we can't guarantee that the `GetHashCode` is telling us it's the same object reference. And we can't be sure what the `GetHashCode` is doing as it can be overwritten (it could be changing because of some internal state for example).
> 
> Info here: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.objectidgenerator?view=netstandard-2.0
> 
> What are your thoughts?

I think yours it's a better way because, in the end, the goal is exactly that: having a way to uniquely identify an instance. While GetHashcode() can be OK, it can be overridden, and could be misused and cause issues in several scenarios. 

I have never used `ObjectIDGenerator`, but I guess it can be very useful for our goal.

**Comment by Gaweph** [comment]
Thanks for this.  Makes much more sense now that instances have their own Cache

**Comment by SuperJMN** [comment]
I'm so happy this made an actual improvement. I'm already using your library internally in a tool, and I plan to release it soon. 
Keep it up!

**Comment by Gaweph** [comment]
For info.  This is the update to use idgenerator :)  Let me know if you have any other improvement ideas etc... :)
https://github.com/Gaweph/Memoizer/commit/0689e970a63a5dd072f327587e0195ea01577410

**Pull request merged**
